### ISSUE TITLE
cjs failed to build

### ISSUE THREAD

**Issue by willysr** [CinnamonSlackBuilds/csb#59]
### Slackware Version
-current

### Cinnamon Version
6.2

### GIT Branch
master

### Description
cjs failed to build since -current moved to newer mozjs-128, while cjs is still relying on mozjs-115
until upstream moves to newer mozjs, we will have to wait and cjs is in broken state for now

**Comment by maia1703** [comment]
diff -ruN cjs-6.2.0-orig/cjs/byteArray.cpp cjs-6.2.0/cjs/byteArray.cpp
--- cjs-6.2.0-orig/cjs/byteArray.cpp	2024-06-11 16:27:18.000000000 +0200
+++ cjs-6.2.0/cjs/byteArray.cpp	2024-10-14 18:35:57.000000000 +0200
@@ -6,11 +6,14 @@
 
 #include <stdint.h>
 
+#include <algorithm>  // for copy_n
+
 #include <glib-object.h>
 #include <glib.h>
 
 #include <js/ArrayBuffer.h>
 #include <js/CallArgs.h>
+#include <js/GCAPI.h>
 #include <js/PropertyAndElement.h>
 #include <js/PropertySpec.h>
 #include <js/RootingAPI.h>
@@ -28,15 +31,6 @@
 #include "cjs/jsapi-util.h"
 #include "cjs/macros.h"
 #include "cjs/text-encoding.h"
-#include "util/misc.h"  // for _gjs_memdup2
-
-// Callback to use with JS::NewExternalArrayBuffer()
-
-static void bytes_unref_arraybuffer(void* contents [[maybe_unused]],
-                                    void* user_data) {
-    auto* gbytes = static_cast<GBytes*>(user_data);
-    g_bytes_unref(gbytes);
-}
 
 GJS_JSAPI_RETURN_CONVENTION
 static bool to_string_func(JSContext* cx, unsigned argc, JS::Value* vp) {
@@ -145,15 +139,18 @@
         return true;
     }
 
-    JS::RootedObject array_buffer(
-        context,
-        JS::NewExternalArrayBuffer(
-            context, len,
-            const_cast<void*>(data),  // the ArrayBuffer won't modify the data
-            bytes_unref_arraybuffer, gbytes));
+    JS::RootedObject array_buffer{context, JS::NewArrayBuffer(context, len)};
     if (!array_buffer)
         return false;
-    g_bytes_ref(gbytes);  // now owned by both ArrayBuffer and BoxedBase
+
+    // Copy the data into the ArrayBuffer so that the copy is aligned, and
+    // because the GBytes data pointer may point into immutable memory.
+    {
+        JS::AutoCheckCannotGC nogc;
+        bool unused;
+        uint8_t* storage = JS::GetArrayBufferData(array_buffer, &unused, nogc);
+        std::copy_n(static_cast<const uint8_t*>(data), len, storage);
+    }
 
     JS::RootedObject obj(
         context, JS_NewUint8ArrayWithBuffer(context, array_buffer, 0, -1));
@@ -164,14 +161,20 @@
     return true;
 }
 
-JSObject* gjs_byte_array_from_data(JSContext* cx, size_t nbytes, void* data) {
+JSObject* gjs_byte_array_from_data_copy(JSContext* cx, size_t nbytes,
+                                        void* data) {
     JS::RootedObject array_buffer(cx);
     // a null data pointer takes precedence over whatever `nbytes` says
-    if (data)
-        array_buffer = JS::NewArrayBufferWithContents(
-            cx, nbytes, _gjs_memdup2(data, nbytes));
-    else
+    if (data) {
+        array_buffer = JS::NewArrayBuffer(cx, nbytes);
+
+        JS::AutoCheckCannotGC nogc{};
+        bool unused;
+        uint8_t* storage = JS::GetArrayBufferData(array_buffer, &unused, nogc);
+        std::copy_n(static_cast<uint8_t*>(data), nbytes, storage);
+    } else {
         array_buffer = JS::NewArrayBuffer(cx, 0);
+    }
     if (!array_buffer)
         return nullptr;
 
@@ -186,7 +189,7 @@
 }
 
 JSObject* gjs_byte_array_from_byte_array(JSContext* cx, GByteArray* array) {
-    return gjs_byte_array_from_data(cx, array->len, array->data);
+    return gjs_byte_array_from_data_copy(cx, array->len, array->data);
 }
 
 GBytes* gjs_byte_array_get_bytes(JSObject* obj) {

**Comment by maia1703** [comment]
You can get the patch (cjs-mozjs128.patch) from me : 

patch  -p1 > $CWD/cjs-mozjs128.patch
  or
cat $CWD/cjs-mozjs128.patch | patch -p1

**Comment by willysr** [comment]
@maia1703 can you wrap it in code block?

**Comment by willysr** [comment]
Fixed by b6accfb

**Comment by willysr** [comment]
well, mozjs115 is no longer available in -current

**Comment by willysr** [comment]
yeah, you are right, it's not yet fixed

**Comment by SpreadiesInSpace** [comment]
https://slackware.nl/slackware-live/latest/

Would it be possible to consume csb packages from the most recent AlienBoB Cinnamon liveslak ISO? Another thing to consider is that this ISO has mozjs115 IIRC.

**Comment by willysr** [comment]
well, if you upgrade to latest update in current, you will notice that mozjs115 is removed, so as long as you don't remove that package, it should be ok

**Comment by willysr** [comment]
maybe i will add mozjs115 as part of CSB in order to avoid breaking cinnamon

**Comment by willysr** [comment]
i reverted the patch and i uploaded the untested mozjs115 script
I will check it again later and see if it builds and fixed the problem with cjs, so I will keep this issue open for now

**Comment by fulalas** [comment]
> well, if you upgrade to latest update in current, you will notice that mozjs115 is removed, so as long as you don't remove that package, it should be ok

You can always download from the cumulative repo:

https://slackware.uk/cumulative/slackware64-current/slackware64/l/mozjs115-115.15.0esr-x86_64-1.txz

**Comment by willysr** [comment]
true, but we tried to stick with what provided by Slackware core packages

**Comment by willysr** [comment]
yes, even with latest 115.17.0 it failed to build on latest -current
i guess we will have to wait for cjs to get ported to newer mozjs

**Comment by fulalas** [comment]
I managed to workaround this issue in current. It implies rebuilding mozjs-115, but that's not a big deal:

1. download recursively all contents from: [ftp.dnslb.sjtu.edu.cn/sites/www.pclinuxos.com/slackware64-current/source/l/mozjs115](url)
2. download to the main folder downloaded above mozjs-115 latest update from here: https://ftp.mozilla.org/pub/firefox/releases/115.17.0esr/source/firefox-115.17.0esr.source.tar.xz
3. download my patches and extract to the main folder downloaded above: [mozjs-115.zip](https://github.com/user-attachments/files/17883013/mozjs-115.zip)
4. build and install `mozjs-115`

Now you can build `cjs` normally.

I rebuilt the whole Cinnamon desktop environment from scratch just to make sure it builds and also runs normally; it's all good. :)

**Comment by willysr** [comment]
Thanks @fulalas  i managed to build it properly :)
i can close this issue now
